
package Compilador;

import Compilador.Token.Tipos;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.PrintWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Henrr
 */
public class Principal extends javax.swing.JFrame {
     String textoArchivo;
     File Archivo;
    public Principal() {
        initComponents();
        guardarArchivo.setEnabled(false);
        btnGrupos.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        NombreArchivo = new javax.swing.JTextField();
        CargarArchivo = new javax.swing.JButton();
        guardarArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoArchivo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoOperaciones = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnGrupos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        NombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreArchivoActionPerformed(evt);
            }
        });

        CargarArchivo.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        CargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compilador/Abrir.png"))); // NOI18N
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });

        guardarArchivo.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        guardarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compilador/Guardar.png"))); // NOI18N
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(153, 204, 255));

        contenidoArchivo.setBackground(new java.awt.Color(204, 204, 255));
        contenidoArchivo.setColumns(20);
        contenidoArchivo.setFont(new java.awt.Font("Monospaced", 2, 10)); // NOI18N
        contenidoArchivo.setRows(5);
        jScrollPane1.setViewportView(contenidoArchivo);

        resultadoOperaciones.setBackground(new java.awt.Color(204, 204, 255));
        resultadoOperaciones.setColumns(20);
        resultadoOperaciones.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        resultadoOperaciones.setRows(5);
        jScrollPane2.setViewportView(resultadoOperaciones);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Consola");

        btnGrupos.setBackground(new java.awt.Color(153, 153, 153));
        btnGrupos.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compilador/Analisis.png"))); // NOI18N
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(CargarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrupos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CargarArchivo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guardarArchivo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        /* String txt="";
        ArrayList<Token> tokens = Lexico(textoArchivo);
        for (Token token : tokens) {
            txt+="(" + token.getTipo() + ": " + token.getValor() +")\n";
        }
        resultadoOperaciones.setText(txt);*/
        Reader lector;
        try {
            lector = new BufferedReader(new FileReader(Archivo));
            Lexer lexer = new Lexer(lector);
            String resultado = "";
            while (true) {
                Tokens tokens = lexer.yylex();
                if (tokens == null) {
                    resultado += "FIN";
                    resultadoOperaciones.setText(resultado);
                    return;
                }
                switch (tokens) {
                    case ERROR:
                    resultado += "Símbolo no definido\n";
                    break;
                    case Identificador: case Numero: case Reservadas:
                    resultado += lexer.lexeme + ": Es un " + tokens + "\n";
                    break;
                    default:
                    resultado += "Token: " + tokens + "\n";
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGruposActionPerformed

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        // TODO add your handling code here:
        if ("".equals(NombreArchivo.getText())) {
            GuardarExpresion();

        } else {
            FileWriter Arc;
            try {
                Arc = new FileWriter(NombreArchivo.getText() + ".txt");
                BufferedWriter Escribe = new BufferedWriter(Arc);
                PrintWriter Escritura = new PrintWriter(Escribe);
                Escritura.println(resultadoOperaciones.getText());
                Escribe.close();
                Escritura.close();
                JOptionPane.showMessageDialog(null, "ARCHIVO GUARDADO");
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        try {
            //Cargamos el archivo
            SeleccionarArchivo();
            
            guardarArchivo.setEnabled(true);
            btnGrupos.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CargarArchivoActionPerformed

    // Eventos de componentes
    private void NombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreArchivoActionPerformed

    //metodos
    public void SeleccionarArchivo() throws FileNotFoundException, IOException {
        JFileChooser Elegir = new JFileChooser();
        Elegir.setDialogTitle("SELECCIONE EL ARCHIVO PARA MOSTRAR");
        Elegir.showOpenDialog(Elegir);
        Archivo = new File(Elegir.getSelectedFile().getAbsolutePath());
         textoArchivo = "";

        if (Archivo.exists() && Archivo.canRead()) {
            FileReader Ar1 = new FileReader(Archivo);
            String Almacena;
            BufferedReader ArIn = new BufferedReader(Ar1);
            while ((Almacena = ArIn.readLine()) != null) {
                textoArchivo += Almacena + "\n";
            }
            ArIn.close();
            contenidoArchivo.setText(textoArchivo);
        } else {
            JOptionPane.showConfirmDialog(null, "ARCHIVO NO EXISTE O NO SE PUEDE LEER ");
        }
    }

    public void GuardarExpresion() {

        try {
            JFileChooser Archi = new JFileChooser();
            Archi.showSaveDialog(Archi);
            File Dir = new File(Archi.getSelectedFile().getAbsolutePath() + ".txt");
            FileWriter Arc = new FileWriter(Dir);
            BufferedWriter Escribe = new BufferedWriter(Arc);
            PrintWriter Escritura = new PrintWriter(Escribe);
            Escritura.println(resultadoOperaciones.getText());
            Escribe.close();
            Escritura.close();
            JOptionPane.showMessageDialog(null, "ARCHIVO GUARDADO");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "NO INGRESO EL NOMBRE NI LA UBICACION DONDE SE GUARDARA EL ARCHIVO");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "EL ARCHIVO NO SE PUEDE ESCRIBIR");
        }
    }
    //Token
      private static ArrayList<Token> Lexico(String input) {
        final ArrayList<Token> tokens = new ArrayList<Token>();
        final StringTokenizer st = new StringTokenizer(input);

        while(st.hasMoreTokens()) {
            String palabra = st.nextToken();
            boolean matched = false;

            for (Tipos tokenTipo : Tipos.values()) {
                Pattern patron = Pattern.compile(tokenTipo.patron, Pattern.MULTILINE);
                Matcher matcher = patron.matcher(palabra);
                if(matcher.find()) {
                    Token tk = new Token();
                    tk.setTipo(tokenTipo);
                    tk.setValor(palabra);
                    tokens.add(tk);
                    matched = true;
                }
            }
            if (!matched) {
                System.err.println("Se encontró un token invalido.");
            }
        }
       return tokens;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JTextField NombreArchivo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JTextArea contenidoArchivo;
    private javax.swing.JButton guardarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultadoOperaciones;
    // End of variables declaration//GEN-END:variables
}
