
package Compilador;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.PrintWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Henrr
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        btnExpresion.setEnabled(false);
        guardarArchivo.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        NombreArchivo = new javax.swing.JTextField();
        CargarArchivo = new javax.swing.JButton();
        guardarArchivo = new javax.swing.JButton();
        areaExpresion = new javax.swing.JTextField();
        btnExpresion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenidoArchivo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoOperaciones = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        NombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreArchivoActionPerformed(evt);
            }
        });

        CargarArchivo.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        CargarArchivo.setText("Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });

        guardarArchivo.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        guardarArchivo.setText("Guardar");
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });

        areaExpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaExpresionActionPerformed(evt);
            }
        });

        btnExpresion.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnExpresion.setText("Validar RegExp");
        btnExpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpresionActionPerformed(evt);
            }
        });

        contenidoArchivo.setColumns(20);
        contenidoArchivo.setFont(new java.awt.Font("Monospaced", 2, 10)); // NOI18N
        contenidoArchivo.setRows(5);
        jScrollPane1.setViewportView(contenidoArchivo);

        resultadoOperaciones.setColumns(20);
        resultadoOperaciones.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        resultadoOperaciones.setRows(5);
        jScrollPane2.setViewportView(resultadoOperaciones);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setText("Consola");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelPrincipalLayout.createSequentialGroup()
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(areaExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(CargarArchivo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(guardarArchivo)
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnExpresion)
                                    .addGap(44, 44, 44))))
                        .addGroup(PanelPrincipalLayout.createSequentialGroup()
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargarArchivo)
                    .addComponent(guardarArchivo))
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnExpresion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //metodos
    public void SeleccionarArchivo() throws FileNotFoundException, IOException {
        JFileChooser Elegir = new JFileChooser();
        Elegir.setDialogTitle("SELECCIONE EL ARCHIVO PARA MOSTRAR");
        Elegir.showOpenDialog(Elegir);
        File Archivo = new File(Elegir.getSelectedFile().getAbsolutePath());
        String Txt = "";

        if (Archivo.exists() && Archivo.canRead()) {
            FileReader Ar1 = new FileReader(Archivo);
            String Almacena;
            BufferedReader ArIn = new BufferedReader(Ar1);
            while ((Almacena = ArIn.readLine()) != null) {
                Txt += Almacena + "\n";
            }
            ArIn.close();
            contenidoArchivo.setText(Txt);
        } else {
            JOptionPane.showConfirmDialog(null, "ARCHIVO NO EXISTE O NO SE PUEDE LEER ");
        }
    }

    public void GuardarExpresion() {

        try {
            JFileChooser Archi = new JFileChooser();
            Archi.showSaveDialog(Archi);
            File Dir = new File(Archi.getSelectedFile().getAbsolutePath() + ".txt");
            FileWriter Arc = new FileWriter(Dir);
            BufferedWriter Escribe = new BufferedWriter(Arc);
            PrintWriter Escritura = new PrintWriter(Escribe);
            Escritura.println(resultadoOperaciones.getText());
            Escribe.close();
            Escritura.close();
            JOptionPane.showMessageDialog(null, "ARCHIVO GUARDADO");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "NO INGRESO EL NOMBRE NI LA UBICACION DONDE SE GUARDARA EL ARCHIVO");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "EL ARCHIVO NO SE PUEDE ESCRIBIR");
        }
    }

    // Eventos de componentes
    private void NombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreArchivoActionPerformed

    private void areaExpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaExpresionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaExpresionActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        try {
            //Cargamos el archivo
            SeleccionarArchivo();
            btnExpresion.setEnabled(true);
            guardarArchivo.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void btnExpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpresionActionPerformed
        String resultado = "";
        final Pattern pattern = Pattern.compile(areaExpresion.getText(), Pattern.MULTILINE);
        final Matcher matcher = pattern.matcher(contenidoArchivo.getText());

        while (matcher.find()) {
            resultado += matcher.group(0) + "\n";
            for (int i = 1; i <= matcher.groupCount(); i++) {
                resultado += matcher.group(i) + "\n";

            }
        }

        resultadoOperaciones.setText(resultado);
    }//GEN-LAST:event_btnExpresionActionPerformed

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        // TODO add your handling code here:
        if ("".equals(NombreArchivo.getText())) {
            GuardarExpresion();

        } else {
            FileWriter Arc;
            try {
                Arc = new FileWriter(NombreArchivo.getText() + ".txt");
                BufferedWriter Escribe = new BufferedWriter(Arc);
                PrintWriter Escritura = new PrintWriter(Escribe);
                Escritura.println(resultadoOperaciones.getText());
                Escribe.close();
                Escritura.close();
                JOptionPane.showMessageDialog(null, "ARCHIVO GUARDADO");
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_guardarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JTextField NombreArchivo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTextField areaExpresion;
    private javax.swing.JButton btnExpresion;
    private javax.swing.JTextArea contenidoArchivo;
    private javax.swing.JButton guardarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultadoOperaciones;
    // End of variables declaration//GEN-END:variables
}
